### PR TITLE
chore: Ensure Mock Tests Run

### PR DESCRIPTION
**Pull request by bbernays**

### CODE REVIEW

**Comment by shimonp21** [comment]
Hmmmmm, I tried (locally, without this commit), to change one of the GCP tables to be `IgnoreInTests`. However, as we discussed yesterday, the corresponding mock test **doesn't** fail!
Couldn't yet figure out why. Feel it's important to figure out because we may have a much bigger issue of GCP mock tests not working properly..

**Comment by bbernays** [comment]
GCP Doesn't fail when mock tests aren't run. This is a known difference between the mocking implementation between AWS/Azure and GCP

**Comment by shimonp21** [comment]
My concern is that I don't understand what do they test, if even **not running** them doesn't make the fail.
Seems like a bad "always passes" test. Do you understand where this difference comes from?

**Comment by shimonp21** [comment]
cc: @roneli

**Comment by bbernays** [comment]
The mock tests that use [mock](https://github.com/golang/mock) (AWS/Azure) have an `EXPECT` call in them that causes a failure when the function is not caused. The GCP Tests do not have this implementation.

**Comment by shimonp21** [comment]
gocha. LGTM.

**Review by shimonp21 — APPROVED** [review]

**Pull request merged**
