### PR TITLE
Drop CRM resource (duplicate)

### PR DESCRIPTION
**Pull request by irmatov**

### CODE REVIEW

**Comment by irmatov** [comment]
@roneli do we need a migration for this?

**Comment by irmatov** [comment]
Closes cloudquery/cloudquery-issues#102

**Review by roneli — CHANGES_REQUESTED** [review]
You need to add drop migration on .up.sql

**Comment by irmatov** [comment]
@roneli added a migration (only "up") with drop table statement.

**Review by roneli — CHANGES_REQUESTED** [review]
LGTM, minor change update the migration to v0.4.6 instead of v0.4.5

**Comment by irmatov** [comment]
renamed migration to 2_v0.4.6.up.sql

**Review by roneli — APPROVED** [review]
LGTM

**Pull request merged**
